#!/bin/sh

set -e

if [ -d xcpkg-formula-repository-official-core ] ; then
    git -C xcpkg-formula-repository-official-core pull
else
    git clone --depth=1 https://ghfast.top/https://github.com/leleliu008/xcpkg-formula-repository-official-core
fi

cd xcpkg-formula-repository-official-core/formula

ls *.yml | sed 's|\.yml$||' | sort | uniq > a

sed -n '/^dep-pkg:/p' *.yml | cut -c10- | tr ' ' '\n' | sort | uniq > b

#######################################################

SWIFT_PKGS=
SWIFT_PKGS2=

for item in nodejs@24 simplex-chat psc-package $(grep -E '(bsystem: swift|install: swiftw)' -rl .)
do
    item="${item#./}"
    item="${item%.yml}"
    SWIFT_PKGS="$SWIFT_PKGS $item"
    SWIFT_PKGS2="$SWIFT_PKGS2, $item"
done

SWIFT_PKGS2="${SWIFT_PKGS2#,}"

#######################################################

SED="sed -e s|^-||"

for item in chisel d8 fortune psutils golang redex koka stack llvm@16 $SWIFT_PKGS
do
    SED="$SED -e /^$item$/d"
done

echo "SED=$SED"

#######################################################

PKGS="$(diff -U 0 a b | sed '/^--/d' | grep '^-' | $SED)"

PKGS_COUNT="$(printf "$PKGS" | wc -l)"
PKGS_COUNT="$(($PKGS_COUNT + 1))"

echo "PKGS_COUNT=$PKGS_COUNT"

cd -

#######################################################

cat > publish.yml <<EOF
name: publish

on:
  workflow_dispatch

jobs:

EOF
        
gsed -e "s|buildN|build0|" -e "s|ITEMS|$SWIFT_PKGS2|" build >> publish.yml

#######################################################

ITEMS=
NEEDS='build0'

I=1
J=0
K=0

for item in $PKGS
do
    ITEMS="$ITEMS, $item"

    K=$(($K + 1))

    J=$(($J + 1))

    echo "J=$J"
    echo "K=$K"

    if [ "$J" = 128 ] || [ "$K" = "$PKGS_COUNT" ] ; then
        gsed -e "s|buildN|build$I|" -e "s|ITEMS|${ITEMS#,}|" build >> publish.yml

        ITEMS=
        NEEDS="$NEEDS, build$I"

        I=$(($I + 1))
        J=0
    fi
done

cat >> publish.yml <<EOF

  publish:
    needs: [$NEEDS]

EOF

cat foot >> publish.yml

mv publish.yml .github/workflows/
